package sofab_test

// The README's `### Code generator` example, as code that actually compiles and
// runs — and a check that the README still shows exactly this code.
//
// The point is drift: a hand-written example in a Markdown file stops matching
// the API the moment the API moves, and nothing notices until a reader copies
// it. Here the example is a real Go file the compiler and the test binary see,
// and the mirror check below fails if the README's fenced block and this file
// ever disagree. Nothing asserts what the README *says* — only that the code in
// it is this code, and that this code works.

import (
	"bytes"
	"os"
	"strings"
	"testing"

	sofab "github.com/sofa-buffers/corelib-go"
)

// _visitorBase is the README's spelling of the no-op Visitor methods a generated
// type embeds; the package ships them as sofab.VisitorBase.
type _visitorBase = sofab.VisitorBase

// --- 8< --- README `### Code generator` ---------------------------------------

// generated by: sofabgen --lang go
type Point struct {
	_visitorBase       // default no-op Visitor methods
	X            int32 `json:"x"`
	Y            int32 `json:"y"`
}

func (m *Point) Serialize(e *sofab.Encoder) {
	e.WriteSigned(1, int64(m.X))
	e.WriteSigned(2, int64(m.Y))
}

func (m *Point) Signed(id sofab.ID, v int64) error {
	switch id {
	case 1:
		m.X = int32(v)
	case 2:
		m.Y = int32(v)
	}
	return nil
}

func (m *Point) Encode() ([]byte, error) {
	var buf bytes.Buffer
	e := sofab.NewEncoder(&buf)
	m.Serialize(e)
	if err := e.Flush(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func DecodePoint(data []byte) (*Point, error) {
	m := &Point{}
	if err := sofab.AcceptBytes(data, m); err != nil {
		return nil, err
	}
	return m, nil
}

// --- >8 --- end of the mirrored block ----------------------------------------

// The example round-trips, and the streaming path produces the same bytes as the
// one-shot one — the two claims the README makes about generated code.
func TestReadmeGeneratorExampleRunsAndRoundTrips(t *testing.T) {
	wire, err := (&Point{X: 3, Y: 4}).Encode()
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	got, err := DecodePoint(wire)
	if err != nil {
		t.Fatalf("DecodePoint: %v", err)
	}
	if got.X != 3 || got.Y != 4 {
		t.Errorf("round trip = (%d, %d), want (3, 4)", got.X, got.Y)
	}

	// The same object through a 1-byte streaming window must produce the same
	// bytes, and decode identically when fed back one byte at a time.
	var streamed bytes.Buffer
	scratch := make([]byte, sofab.MinOutputBuffer)
	e, err := sofab.NewEncoderSink(scratch, 0, func(_ *sofab.Encoder, b []byte) error {
		streamed.Write(b)
		return nil
	})
	if err != nil {
		t.Fatalf("NewEncoderSink: %v", err)
	}
	(&Point{X: 3, Y: 4}).Serialize(e)
	if err := e.Flush(); err != nil {
		t.Fatalf("Flush: %v", err)
	}
	if !bytes.Equal(streamed.Bytes(), wire) {
		t.Errorf("streamed bytes %x != one-shot bytes %x", streamed.Bytes(), wire)
	}

	chunked := &Point{}
	d := sofab.NewDecoder(chunked)
	var out sofab.Outcome
	for i := range wire {
		var err error
		if out, err = d.Feed(wire[i : i+1]); err != nil {
			t.Fatalf("Feed: %v", err)
		}
	}
	if out != sofab.Complete {
		t.Fatalf("last Feed = %v, want COMPLETE", out)
	}
	if chunked.X != 3 || chunked.Y != 4 {
		t.Errorf("streamed decode = (%d, %d), want (3, 4)", chunked.X, chunked.Y)
	}
}

// Every line of the README's Go example must stand, in order, in this file. A
// README that drifts from the compiled example fails here rather than in a
// reader's editor.
func TestReadmeGeneratorExampleIsTheCodeThisFileCompiles(t *testing.T) {
	readme, err := os.ReadFile("README.md")
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	block := goBlockOf(t, string(readme), "### Code generator")
	self, err := os.ReadFile("readme_example_test.go")
	if err != nil {
		t.Fatalf("read self: %v", err)
	}
	mirror := string(self)

	at := 0
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "// use:") {
			break // what follows is statement code; it lives in the test above
		}
		if line == "" {
			continue
		}
		i := strings.Index(mirror[at:], line)
		if i < 0 {
			t.Errorf("README shows a line this file does not compile (or shows it out of order):\n\t%s", line)
			continue
		}
		at += i + len(line)
	}
}

// goBlockOf returns the first ```go fence inside the named section.
func goBlockOf(t *testing.T, doc, heading string) string {
	t.Helper()
	i := strings.Index(doc, heading)
	if i < 0 {
		t.Fatalf("README has no %q section", heading)
	}
	rest := doc[i:]
	if end := strings.Index(rest[len(heading):], "\n## "); end >= 0 {
		rest = rest[:len(heading)+end]
	}
	start := strings.Index(rest, "```go")
	if start < 0 {
		t.Fatalf("%q has no ```go example", heading)
	}
	rest = rest[start+len("```go"):]
	end := strings.Index(rest, "```")
	if end < 0 {
		t.Fatalf("%q has an unterminated code fence", heading)
	}
	return rest[:end]
}
